---
extends:
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:prettier/recommended

plugins:
  - prettier

parserOptions:
  project:
    - tsconfig.eslint.json
    - src/tsconfig.json
    - test/tsconfig.json

rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  no-duplicate-imports: off
  curly:
    - error
    - multi-line
  '@typescript-eslint/no-unsafe-enum-comparison': off
  '@typescript-eslint/restrict-plus-operands': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/consistent-type-definitions':
    - error
    - interface
  '@typescript-eslint/prefer-literal-enum-member':
    - error
    - allowBitwiseExpressions: true
  # The following rule conflicts with Prettier. See
  # https://github.com/typescript-eslint/typescript-eslint/issues/1824.
  '@typescript-eslint/indent': off
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
