name: CI

on:
  push:
  pull_request:

jobs:
  run-eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Node.js v19
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v2

  build-project:
    name: Compile source code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Node.js v19
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Register problem matcher
        run: echo "##[add-matcher].github/problem-matchers/tsc.json"

      - name: Compile TypeScript
        run: pnpm build
